version: 2.1
jobs:
    - Install-Dependencies:
      docker:
        - image: node:14-alpine
      steps:
        - run:
            name: install needed dependcies
            command: npm i 
    - Build-Application:
      docker:
        - image: node:14-alpine
      steps:
        - run:
            name: build angular frontend
            command: ng build
    - Start-Backend-Server:
      docker:
        - image: node:14-alpine
      steps:
        - run:
            name: start json server
            command: npm server
    - Complete:
      docker:
        - image: node:14-alpine
      steps:
        - run: 
            name: let me know that the jobs ran successfully
            command: echo "Jobs completed"
workflows:
  Build-Start-Server-Workflow:
      jobs:
        - Install-Dependencies
        - Build-Application:
            requires: 
              - Install-Dependencies
        - ApproveFrontend-Build:
        #Approve the workflow to continue after 
        #the install dependencies job and build application 
        #job has successfully completed
            type: approval
            requires: 
              - Install-Dependencies
              - Build-Application
        - Start-Backend-Server:
            requires:
              - Install-Dependencies
              - Build-Application
        - Complete


