version: 2.1
jobs:
  build:
    docker: 
      - image: node:14.19.3-alpine
    steps:
      - run:
          name: build aplication
          command: | 
                    npm i
                    npm build
