version: 2.1
jobs:
    Build-Application:
      docker:
        - image: node:16.15.1-alpine
      steps:
        - checkout
        - restore_cache:
            key:  -v1- {{checksum "package-lock.json"}}
        - run:
            name: install dependencies
            command: npm i 
        - save_cache:
            key: -v1- {{checksum "package-lock.json"}}
            paths:
              - /node_modules
workflows:
  Cach-Workflow:
    jobs:
      - Build-Application
