version: 2.1
jobs:
    Build-Application:
      docker:
        - image: node:14-alpine
      steps:
        - run:
            name: install dependencies
            command:  | 
                        npm i
                        ng build
    Start-Backend-Server:
      docker:
        - image: node:14-alpine
      steps:
        - checkout
        - run:
            name: start json server
            command: npm server
    Complete:
      docker:
        - image: node:14-alpine
      steps:
        - run: 
            name: let me know that the jobs ran successfully
            command: echo "Jobs completed"
workflows:
  Build-Start-Server-Workflow:
      jobs:
        - Build-Application
        - ApproveFrontend-Build:
        #Approve the workflow to continue after 
        #the install dependencies job and build application 
        #job has successfully completed
            type: approval
            requires: 
              - Build-Application
        - Start-Backend-Server:
            requires:
              - Build-Application
        - Complete


