version: 2.1
jobs:
    Build-Application:
      docker:
        - image: node:16.15.1-alpine
      steps:
        - checkout
        - restore_cache:
            keys:
            - my-cache
        - run:
            name: install dependencies
            command: npm i 
        - save_cache:
            key: my-cache
            paths:
              - todo-app/node_modules
workflows:
  Cach-Workflow:
    jobs:
      - Build-Application
