version: 2.1
jobs:
  build:
    docker: 
      - image: node:14.19.3-alpine
    steps:
      - run: 
          name: install dependencies
          command: npm i 
      - run:
          name: build angular frontend application
          command:  |
                    npm build
                    echo "build was successful"
