version: 2.1
jobs:
    Build-Application:
      docker:
        - image: node:16.15.1-alpine
      steps:
        - checkout
        - run:
            name: install dependencies
            command:  | 
                        npm i
                        npm run build
    Serve-App:
      docker:
        - image: node:16.15.1-alpine
      steps:
        - checkout
        - run:
            name: serve application
            command: | 
                      npm i
                      npm run serve
workflows:
  Build-Start-Server-Workflow:
      jobs:
        - Build-Application
        - ApproveFrontend-Build:
            type: approval
            requires: 
              - Build-Application
        - Serve-App

             


