version: 2.1
jobs:
  Install-Dependencies:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - restore_cache:
          key: -v3- {{checksum "package.json"}}
      - run: npm install
      - save_cache:
          key: -v3- {{checksum "package.json"}}
          paths:
            - node_modules
workflows:
  Cache-Workflow:
    jobs:
      - Install-Dependencies